.\"  SVC tools -- the SVC (Systems Validation Centre) tool set
.\"
.\"  Copyright (C) 2000  Stichting Mathematisch Centrum, Amsterdam,
.\"                      The  Netherlands
.\"
.\"  This program is free software; you can redistribute it and/or
.\"  modify it under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"
.\"  This program is distributed in the hope that it will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"
.\"  You should have received a copy of the GNU General Public License
.\"  along with this program; if not, write to the Free Software
.\"  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
.\"
.\" $Id: svc2aut.4,v 1.2 2001/01/04 15:55:42 izak Exp $
.TH SVC2AUT 1 15/5/2000
.SH NAME
svc2aut \- file conversion from SVC format to Aldebaran format

.SH SYNOPSIS
.B svc2aut
[-c][-v][-s][-h][-o 
.I 
outfile\c
] 
.I 
infile

.SH DESCRIPTION
.B svc2aut
is a tool for the conversion of files in SVC format (.svc) to files in
Aldebaran format (.aut)

.SH OPTIONS 
.IP \-c
Don't overwrite existing files
.IP \-v
Print version number
.IP \-h
List available options
.IP \-o\ \fIoutfile\fR
Write the output to \fIoutfile\fR. The default is 
.I outfile.aut
.IP \-s
Silent operation: don't print the header information from the input file

.SH FILES
.IP filename.aut
A file in Aldebaran format
.IP filename.svc
A file in SVC format

.SH SEE ALSO

aut2svc(4)

.SH AUTHOR
Izak van Langevelde <izak@cwi.nl>
.LP
Please send all complaints, comments and bug fixes to me. 
