.\"  SVC tools -- the SVC (Systems Validation Centre) tool set
.\"
.\"  Copyright (C) 2000  Stichting Mathematisch Centrum, Amsterdam,
.\"                      The  Netherlands
.\"
.\"  This program is free software; you can redistribute it and/or
.\"  modify it under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"
.\"  This program is distributed in the hope that it will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"
.\"  You should have received a copy of the GNU General Public License
.\"  along with this program; if not, write to the Free Software
.\"  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
.\"
.\" $Id: svcinfo.4,v 1.2 2001/01/04 15:55:42 izak Exp $
.TH SVCINFO 1 15/5/2000 
.SH NAME
svcinfo \- show the header information of an SVC file

.SH SYNOPSIS
.B svcinfo
[-v][-h]
.I 
infile

.SH DESCRIPTION
.B svcinfo
shows the header information of an SVC file

.SH OPTIONS 
.IP \-v
Print version number
.IP \-h
List available options

.SH FILES
.IP filename.svc
A file in SVC format

.SH AUTHOR
Izak van Langevelde <izak@cwi.nl>
.LP
Please send all complaints, comments and bug fixes to me. 
