.\"  SVC -- the SVC (Systems Validation Centre) file format library
.\"
.\"  Copyright (C) 2000  Stichting Mathematisch Centrum, Amsterdam,
.\"                      The  Netherlands
.\"
.\"  This program is free software; you can redistribute it and/or
.\"  modify it under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"
.\"  This program is distributed in the hope that it will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"
.\"  You should have received a copy of the GNU General Public License
.\"  along with this program; if not, write to the Free Software
.\"  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
.\"
.\" $Id: svcgetformatversion.4,v 1.2 2001/01/04 15:26:33 izak Exp $
.TH SVCgetFormatVersion 4 15/5/2000
.SH NAME
SVCgetVersion \- get the version of an SVC file

.SH SYNOPSIS
#include <svc.h>

char *SVCgetFormatVersion(SVCfile *file\c
);

.SH DESCRIPTION

The SVCgetFormatVersion() function returns 
a pointer to the character string containing the SVC format version 
of 
.I *file
that remains valid until 
.I *file
is closed, or a NULL pointer if errors occurred.


.SH ERRORS

The SVCgetFormatVersion() function fails if...


.SH AUTHOR
Izak van Langevelde <izak@cwi.nl>
.LP
Please send all complaints, comments and bug fixes to the author. 

