.\"  SVC -- the SVC (Systems Validation Centre) file format library
.\"
.\"  Copyright (C) 2000  Stichting Mathematisch Centrum, Amsterdam,
.\"                      The  Netherlands
.\"
.\"  This program is free software; you can redistribute it and/or
.\"  modify it under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"
.\"  This program is distributed in the hope that it will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"
.\"  You should have received a copy of the GNU General Public License
.\"  along with this program; if not, write to the Free Software
.\"  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
.\"
.\" $Id: svcsetcomments.4,v 1.2 2001/01/04 15:26:35 izak Exp $
.TH SVCsetComments 4 15/5/2000
.SH NAME
SVCsetComments \- set the comments of an SVC file

.SH SYNOPSIS
#include <svc.h>

int SVCsetComments(SVCfile 
.I *file,
char 
.I *comments\c
);

.SH DESCRIPTION

The SVCsetComments() function sets the comments 
in the file pointed to by 
.I file,
to 
.I comments

.SH RETURN VALUE

The SVCsetComments() function returns 0 if no errors occurred, or a value <0
otherwise.

.SH ERRORS

The SVCsetComments() function fails if...

.SH SEE ALSO

SVCgetComments(4)

.SH AUTHOR
Izak van Langevelde <izak@cwi.nl>
.LP
Please send all complaints, comments and bug fixes to the author. 

